[versions]
room = "2.6.1"
datastore = "1.1.1"
core-ktx = "1.13.1"
activity-compose = "1.9.0"
compose-bom = "2024.05.00"
compose-ui = "1.6.7"
compose-material3 = "1.3.0-beta01"
compose-material3-adaptive = "1.0.0-beta01"
lifecycle = "2.8.1"
exifinterface = "1.3.7"
navigation = "2.7.7"
documentfile = "1.0.1"

test-ext-junit = "1.1.5"
test-espresso-core = "3.5.1"


[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose-ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-ui" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-material3-window-size-cls = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "compose-material3" }
compose-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "compose-material3" }
compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "compose-material3-adaptive" }
compose-material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "compose-material3-adaptive" }
compose-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "compose-material3-adaptive" }

lifecycle-lifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-lifecycleRuntimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }

navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }


test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "test-ext-junit" }
test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "test-espresso-core" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui" }

compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui" }


[plugins]
room = { id = "androidx.room", version.ref = "room" }
