[versions]
androidGradlePlugin = "8.7.0"

kotlin = "2.0.21"
ksp = "2.0.21-1.0.25"

opencv = "4.10.0"

io-sentry-sentryAndroid = "7.14.0"

apache-commons-io = "2.4"
github-requery-sqlite-android = "3.43.0"
threetenabp = "1.4.6"
compose-richtext = "0.17.0"
github-jvziyaoyao-scale = "1.1.0-alpha.4"
github-cheonjaeung-gridlayout = "2.0.0"
aboutlibraries = "11.2.3"

junit = "4.13.2"

dependencyAnalysis = "1.32.0"


[libraries]
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.7.3" }

opencv = { module = "org.opencv:opencv", version.ref = "opencv" }
protobuf-protobufJavalite = { module = "com.google.protobuf:protobuf-javalite", version = "3.21.12" }

io-sentry-sentryAndroid = { module = "io.sentry:sentry-android", version.ref = "io-sentry-sentryAndroid" }

onnxruntime-android = { module = "com.microsoft.onnxruntime:onnxruntime-android", version = "1.18.0" }

apache-commons-io = { module = "org.apache.directory.studio:org.apache.commons.io", version.ref = "apache-commons-io" }
github-requery-sqlite-android = { module = "com.github.requery:sqlite-android", version.ref = "github-requery-sqlite-android" }
threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }
compose-richtext-commonmark = { module = "com.halilibo.compose-richtext:richtext-commonmark", version.ref = "compose-richtext" }
compose-richtext-ui-material3 = { module = "com.halilibo.compose-richtext:richtext-ui-material3", version.ref = "compose-richtext" }
github-jvziyaoyao-scale-imageViewer = { module = "com.jvziyaoyao.scale:image-viewer", version.ref = "github-jvziyaoyao-scale" }
github-cheonjaeung-gridlayout = { module = "com.cheonjaeung.compose.grid:grid", version.ref = "github-cheonjaeung-gridlayout" }
aboutlibrariesCore = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
aboutlibrariesComposeM3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }

junit = { module = "junit:junit", version.ref = "junit" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }

secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version = "2.0.1" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidGitVersion = { id = "com.gladed.androidgitversion", version = "0.4.14" }

aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }

dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
